<?php 
define('IN_EDITOR', true);
include("header.php");

if ( !$eq2->CheckAccess(M_GUILDS) )
{
	die("Access denied!");
}
include("../class/eq2.guilds.php");



//FUNC INIT VARIABLES
global $eq2;
$eq2Guilds = new eq2Guilds();
$strOffset = str_repeat("\x20",22);
$strHTML = "";
$guilds_data = "";
$guild_data = "";
$event_type_data = "";
$recruiting_data = "";

//SANITIZE _GET DATA
$action = (isset($_GET['action'])?$_GET['action']:"");
$type = (isset($_GET['type'])?$_GET['type']:"");
$id = (isset($_GET['id'])?$_GET['id']:"");
$tab = (isset($_GET['tab'])?$_GET['tab']:"guild");

//FORM HANDLING (Insert/Update/Delete)
if( isset($_POST['cmd']) ) 
{
	switch(strtolower($_POST['cmd'])) {
		case "insert":
			$eq2Guilds->PreInsert();
			$insert_res = $eq2->ProcessInserts();
			$eq2Guilds->PostInsert($insert_res);
		break;
		case "update":
			$eq2Guilds->PreUpdate();
			$eq2->ProcessUpdates();
			$eq2Guilds->PostUpdate();
			break;
		case "delete": 
			$eq2->ProcessDeletes();
			$eq2Guilds->PostDeletes(); 
			break;
		case "multiinsert":
			$eq2->ProcessMultiInsert();
			break;
	}
}

//SEARCH SECTION
$strHTML .= $strOffset . "&nbsp;\n";
$strHTML .= $strOffset . "<fieldset>\n";
$strHTML .= $strOffset . "  <legend>List/Search By:</legend>\n";
$strHTML .= $strOffset . "  <table width='100%'>\n";
$strHTML .= $strOffset . "    <tr>\n";
$strHTML .= $strOffset . "      <td>\n";
$strHTML .= $strOffset . "        <button onclick=\"location.href='guilds.php?action=search&type=name'\">Name</button>\n";
$strHTML .= $strOffset . "        <button onclick=\"location.href='guilds.php?action=search&type=style'\">Play Style</button>\n";
$strHTML .= $strOffset . "        <button onclick=\"location.href='guilds.php?action=byAll'\">All</button>\n";
$strHTML .= $strOffset . "      </td>\n";
$strHTML .= $strOffset . "      <td align='right'>\n";
$strHTML .= $strOffset . "        <button onclick=\"location.href='guilds.php?action=new'\">New</button>\n";
$strHTML .= $strOffset . "      </td>\n";
$strHTML .= $strOffset . "    </tr>\n";
$strHTML .= $strOffset . "    <tr>\n";
$strHTML .= $strOffset . "      <td colspan='2'>\n";
if($action == "search")
{
	switch ($type)
	{
		case "name":
			$search_data = "name";
			$strHTML .= $strOffset . "<script>\n";
			$strHTML .= $strOffset . "  function handleSearchSuggest()\n";
			$strHTML .= $strOffset . "  {\n";
			$strHTML .= $strOffset . "    if (searchReq.readyState == 4)\n";
			$strHTML .= $strOffset . "    {\n";
			$strHTML .= $strOffset . "      let ssdiv = searchSuggestDiv == null ? \"search_suggest\" : searchSuggestDiv;\n";
			$strHTML .= $strOffset . "      searchSuggestDiv = null;\n";
			$strHTML .= $strOffset . "      var ss = document.getElementById(ssdiv);\n";
			$strHTML .= $strOffset . "      ss.innerHTML = '';\n";
			$strHTML .= $strOffset . "      var str = searchReq.responseText.split(\"\\n\");\n";
			$strHTML .= $strOffset . "      for(i=0; i < str.length; i++) \n";
			$strHTML .= $strOffset . "      {\n";
			$strHTML .= $strOffset . "        var suggest = '<div onmouseover=\"suggestOver(this);\" ';\n";
			$strHTML .= $strOffset . "        suggest += 'onmouseout=\"suggestOut(this);\" ';\n";
			$strHTML .= $strOffset . "        if (!str[i].includes(\"No matches.\")) suggest += 'onclick=\"setSearch(this.innerHTML,\\'' + ssdiv + '\\');\" ';\n";
			$strHTML .= $strOffset . "          suggest += 'class=\"suggest_link\">' + str[i] + '</div>';\n";
			$strHTML .= $strOffset . "          ss.innerHTML += suggest;\n";
			$strHTML .= $strOffset . "          ss.className = 'suggest_shadow';\n";
			$strHTML .= $strOffset . "      }\n";
			$strHTML .= $strOffset . "    }\n";
			$strHTML .= $strOffset . "  }\n";
			$strHTML .= $strOffset . "  function AjaxSelect() {\n";
			$strHTML .= $strOffset . "    let e = document.getElementById('txtSearch');\n";
			$strHTML .= $strOffset . "    //Find the selected item type and id via regex\n";
			$strHTML .= $strOffset . "    const pat = /\((\d+)\)$/;\n";
			$strHTML .= $strOffset . "    const m = e.value.match(pat);\n";
			$strHTML .= $strOffset . "    window.location.search = \"?action=display&id=\" + m[1];\n";
			$strHTML .= $strOffset . "  }\n";
			$strHTML .= $strOffset . "  function LookupAJAX() {\n";
			$strHTML .= $strOffset . "    if (searchReq.readyState == 4 || searchReq.readyState == 0) {\n";
			$strHTML .= $strOffset . "      let str = escape(document.getElementById('txtSearch').value);\n";
			$strHTML .= $strOffset . "      if (str.length < 3) {\n";
			$strHTML .= $strOffset . "        let ss = document.getElementById('search_suggest')\n";
			$strHTML .= $strOffset . "        ss.innerHTML = '';\n";
			$strHTML .= $strOffset . "        return;\n";
			$strHTML .= $strOffset . "      }\n";
			$strHTML .= $strOffset . "      searchReq.open(\"GET\", '../ajax/eq2Ajax.php?type=eq2emu_guildname&search=' + str, true);\n";
			$strHTML .= $strOffset . "      searchReq.onreadystatechange = handleSearchSuggest; \n";
			$strHTML .= $strOffset . "      ajaxSelectCallback = AjaxSelect;\n";
			$strHTML .= $strOffset . "      searchReq.send(null);\n";
			$strHTML .= $strOffset . "    }\n";
			$strHTML .= $strOffset . "  }\n";
			$strHTML .= $strOffset . "</script>\n";
			$strHTML .= $strOffset . "<form method='post' name='form1'>\n";
			$strHTML .= $strOffset . "  <input type='text' id='txtSearch' name='GuildName' autocomplete='off' size='40' value='" . stripslashes($_POST['returnVal']) . "' onkeyup='LookupAJAX();' />\n";
			$strHTML .= $strOffset . "  <div id='search_suggest'></div>\n";
			$strHTML .= $strOffset . "  <input type='submit' name='submit' value='Search'>\n";
			$strHTML .= $strOffset . "</form>\n";
			break;
		case "style":
			$strHTML .= $strOffset . "    <select name='transporters_sel' onchange='dosub(this.options[this.selectedIndex].value)'>\n";
			$strHTML .= $strOffset . "      <option>Make Selection</option>\n";
			foreach($search_data as $option)
			{
				$strHTML .= $strOffset . "    <option value='server.php?page=transporters&action=by" . ucfirst($type) . "&id=" . ($option['selValue'] >0?$option['selValue']:$option['selLabel']) . "'>" . $option['selLabel'] . "</option>\n";
			}
			$strHTML .= $strOffset . "    <select>\n";
			break;
		default:
			//NOT IMPLIMENTED
			break;
	}

}
$strHTML .= $strOffset . "      </td>\n";
$strHTML .= $strOffset . "    </tr>\n";
$strHTML .= $strOffset . "  </table>\n";
$strHTML .= $strOffset . "</fieldset>\n";

//LIST SETUP SECTION
switch($action)
{
	case "byAll":
		$label_desc = "All Guilds";
		$guilds_query = "SELECT * FROM `" . ACTIVE_DB . "`.`guilds`";
		$guilds_data = $eq2->RunQueryMulti($guilds_query);
		break;
	case "new":
		$label_desc = "New Guild";
		break;
	case "display":
		switch($tab)
		{
			case "guild_achievements":
				$label_desc = "Guild Achievements";
				break;
			case "guild_recruiting":
				$label_desc = "Guild Recruiting (Guild: " . $id . ")";
				$recruiting_query = "SELECT * FROM `" . ACTIVE_DB . "`.`guild_recruiting` WHERE guild_id = " . $id;
				$recruiting_data = $eq2->RunQuerySingle($recruiting_query);
				break;
			case "guild_bank_settings":
				$label_desc = "Guild Bank Data";
				break;
			case "guild_members":
				$label_desc = "Guild Members";
				$members_query = "SELECT * FROM `" . ACTIVE_DB . "`.`guild_members` WHERE guild_id = " . $id;
				$members_data = $eq2->RunQueryMulti($members_query);
				$ranks_query = "SELECT * FROM `" . ACTIVE_DB . "`.`guild_ranks` WHERE guild_id = " . $id;
				$ranks_data = $eq2->RunQueryMulti($ranks_query);
				break;
			default:
				$label_desc = "Guild Data";
				$guild_query = "SELECT id, name, motd, level, xp, xp_needed, formed_on, DATE(FROM_UNIXTIME(formed_on)) as date FROM `" . ACTIVE_DB . "`.`guilds` WHERE id=" . $id;
				$guild_data = $eq2->RunQuerySingle($guild_query);
				$events_query = "SELECT id, guild_id, event_id, event_date, DATE(FROM_UNIXTIME(event_date)) as date, event_type, description, display, locked, archived FROM `" . ACTIVE_DB . "`.`guild_events` WHERE guild_id = " . $guild_data['id'] . " ORDER BY event_date DESC";
				$events_data = $eq2->RunQueryMulti($events_query);
				$event_max_query = "SELECT MAX(event_id) as max FROM `" . ACTIVE_DB . "`.`guild_events` WHERE guild_id=" . $guild_data['id'];
				$event_max_data = $eq2->RunQuerySingle($event_max_query);
				$event_type_query = "SELECT event_id as type_id, event_name as type_name FROM `" . ACTIVE_DB . "`.`guild_event_defaults`";
				$event_type_data = $eq2->RunQueryMulti($event_type_query);
				break;
		}
		break;
}


//LIST SECTION
if($guilds_data != "")
{
	$strHTML .= $strOffset . "<table>\n";
	$strHTML .= $strOffset . "  <tr>\n";
	$strHTML .= $strOffset . "    <td valign='top'>\n";
	$strHTML .= $strOffset . "      <fieldset>\n";
	$strHTML .= $strOffset . "        <legend>" . $label_desc . "</legend>\n";
	$strHTML .= $strOffset . "        <table class='ContrastTable'>\n";
	$strHTML .= $strOffset . "          <tr>\n";
	$strHTML .= $strOffset . "            <th>ID</th>\n";
	$strHTML .= $strOffset . "            <th>Name</th>\n";
	$strHTML .= $strOffset . "            <th>Level</th>\n";
	$strHTML .= $strOffset . "            <th></th>\n";
	$strHTML .= $strOffset . "          </tr>\n";
	foreach($guilds_data as $guilds)
	{
		$strHTML .= $strOffset . "          <tr>\n";
		$strHTML .= $strOffset . "            <td>" . $guilds['id'] . "</td>\n";
		$strHTML .= $strOffset . "            <td>" . $guilds['name'] . "</td>\n";
		$strHTML .= $strOffset . "            <td>" . $guilds['level'] . "</td>\n";
		$strHTML .= $strOffset . "            <td>\n";
		$strHTML .= $strOffset . "              <button onclick=\"location.href='guilds.php?action=display&id=" . $guilds['id'] . "'\">Edit</button>\n";
		$strHTML .= $strOffset . "            </td>\n";
		$strHTML .= $strOffset . "          </tr>\n";
	}
	$strHTML .= $strOffset . "        </table>\n";
	$strHTML .= $strOffset . "      </fieldset>\n";
	$strHTML .= $strOffset . "    </td>\n";
	$strHTML .= $strOffset . "  </tr>\n";
	$strHTML .= $strOffset . "</table>\n";
}
//NEW GUILD FORM
if($action == "new")
{
	$strHTML .= $strOffset . "<table>\n";
	$strHTML .= $strOffset . "  <tr>\n";
	$strHTML .= $strOffset . "    <td valign='top'>\n";
	$strHTML .= $strOffset . "      <fieldset>\n";
	$strHTML .= $strOffset . "        <legend>" . $label_desc . "</legend>\n";
	$strHTML .= $strOffset . "        <table class='ContrastTable'>\n";
	$strHTML .= $strOffset . "          <tr>\n";
	$strHTML .= $strOffset . "            <th>ID</th>\n";
	$strHTML .= $strOffset . "            <th>Name</th>\n";
	$strHTML .= $strOffset . "            <th>MOTD</th>\n";
	$strHTML .= $strOffset . "            <th>Level</th>\n";
	$strHTML .= $strOffset . "            <th>XP</th>\n";
	$strHTML .= $strOffset . "            <th>XP Needed</th>\n";
	$strHTML .= $strOffset . "            <th>Formed On</th>\n";
	$strHTML .= $strOffset . "            <th></th>\n";
	$strHTML .= $strOffset . "          </tr>\n";
	$strHTML .= $strOffset . "          <form method='post' name='guilds|new'>\n";
	$strHTML .= $strOffset . "            <tr>\n";
	$strHTML .= $strOffset . "              <td>\n";
	$strHTML .= $strOffset . "                New\n";
	$strHTML .= $strOffset . "              </td>\n";
	$strHTML .= $strOffset . "              <td>\n";
	$strHTML .= $strOffset . "                <input type='text' name='guilds|name' style='width:200px;'>\n";
	$strHTML .= $strOffset . "              </td>\n";
	$strHTML .= $strOffset . "              <td>\n";
	$strHTML .= $strOffset . "                <input type='text' name='guilds|motd' style='width:250px;'>\n";
	$strHTML .= $strOffset . "              </td>\n";
	$strHTML .= $strOffset . "              <td>\n";
	$strHTML .= $strOffset . "                <input type='text' name='guilds|level' style='width:40px;'>\n";
	$strHTML .= $strOffset . "              </td>\n";
	$strHTML .= $strOffset . "              <td>\n";
	$strHTML .= $strOffset . "                <input type='text' name='guilds|xp' style='width:70px;'>\n";
	$strHTML .= $strOffset . "              </td>\n";
	$strHTML .= $strOffset . "              <td>\n";
	$strHTML .= $strOffset . "                <input type='text' name='guilds|xp_needed' style='width:70px;'>\n";
	$strHTML .= $strOffset . "              </td>\n";
	$strHTML .= $strOffset . "              <td>\n";
	$strHTML .= $strOffset . "                <input type='text' name='guilds|formed_on' value='" . time() . "'  style='width:85px;' readonly>\n";
	$strHTML .= $strOffset . "              </td>\n";
	$strHTML .= $strOffset . "              <td>\n";
	$strHTML .= $strOffset . "                <input type='hidden' name='table_name' value='guilds' />\n";
	$strHTML .= $strOffset . "                <input type='hidden' name='idx_name' value='id' />\n";
	$strHTML .= $strOffset . "                <input type='submit' name='cmd' value='Insert'>\n";
	$strHTML .= $strOffset . "              </td>\n";
	$strHTML .= $strOffset . "            </tr>\n";
	$strHTML .= $strOffset . "          </form>\n";
	$strHTML .= $strOffset . "        </table>\n";
	$strHTML .= $strOffset . "      </fieldset>\n";
	$strHTML .= $strOffset . "    </td>\n";
	$strHTML .= $strOffset . "  </tr>\n";
	$strHTML .= $strOffset . "</table>\n";
}
//MAIN BODY CONTENT SECTION
if($id != "")
{
	$strHTML .= $strOffset . "<table>\n";
	$strHTML .= $strOffset . "  <tr>\n";
	$strHTML .= $strOffset . "    <td valign='top'>\n";
	$strHTML .= $strOffset . "      <fieldset>\n";
	$strHTML .= $strOffset . "        <legend>" . $label_desc . "</legend>\n";
	$link = $_SERVER['SCRIPT_NAME'] . "?action=display";
	$strHTML .= $strOffset . $eq2->ReturnTabGenerator($_GET['tab'] ?? 'guilds', $eq2Guilds->GetTabArray(), $link);
	switch($tab)
	{
		case "guild_members":
			$strHTML .= $strOffset . "        <fieldset>\n";
			$strHTML .= $strOffset . "          <legend>Members</legend>\n";
			$strHTML .= $strOffset . "          <table class='ContrastTable'>\n";
			$strHTML .= $strOffset . "            <tr>\n";
			$strHTML .= $strOffset . "              <th>ID</th>\n";
			$strHTML .= $strOffset . "              <th>Guild ID</th>\n";
			$strHTML .= $strOffset . "              <th>Char ID</th>\n";
			$strHTML .= $strOffset . "              <th>Recruiter ID</th>\n";
			$strHTML .= $strOffset . "              <th>Guild Status</th>\n";
			$strHTML .= $strOffset . "              <th>Points</th>\n";
			$strHTML .= $strOffset . "              <th>Rank ID</th>\n";
			$strHTML .= $strOffset . "              <th>Member Flags</th>\n";
			$strHTML .= $strOffset . "              <th>Join Date</th>\n";
			$strHTML .= $strOffset . "              <th>Note</th>\n";
			$strHTML .= $strOffset . "              <th>Officer Note</th>\n";
			$strHTML .= $strOffset . "              <th>Recruiting Msg</th>\n";
			$strHTML .= $strOffset . "              <th></th>\n";
			$strHTML .= $strOffset . "            </tr>\n";
			$strHTML .= $strOffset . "            <form method='post' name='guild_members|new'>\n";
			$strHTML .= $strOffset . "              </tr>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  New\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guild_members|guild_id' value='" . $id . "' style='width:35px;' readonly>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guild_members|char_id' style='width:70px;'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guild_members|recruiter_id' style='width:70px;'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guild_members|guild_status' style='width:55px;'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guild_members|points' style='width:40px;'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guild_members|rank_id' style='width:25px;'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guild_members|member_flags' style='width:35px;'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guild_members|join_date' value='" . time() . "' style='width:85px;'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guild_members|note'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guild_members|officer_note'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guild_members|recruiting_message'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='hidden' name='table_name' value='guild_members' />\n";
			$strHTML .= $strOffset . "                  <input type='hidden' name='idx_name' value='id' />\n";
			$strHTML .= $strOffset . "                  <input type='submit' name='cmd' value='Insert'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "              </tr>\n";
			$strHTML .= $strOffset . "            </form>\n";
			foreach($members_data as $member)
			{
				$strHTML .= $strOffset . "            <tr>\n";
				$strHTML .= $strOffset . "              <td>\n";
				$strHTML .= $strOffset . "                <input type='text' value='" . $member['id'] . "' style='width:55px;' readonly>\n";
				$strHTML .= $strOffset . "              </td>\n";
				$strHTML .= $strOffset . "              <td>\n";
				$strHTML .= $strOffset . "                <input type='text' value='" . $member['guild_id'] . "' style='width:35px;' readonly>\n";
				$strHTML .= $strOffset . "              </td>\n";
				$strHTML .= $strOffset . "              <td>\n";
				$strHTML .= $strOffset . "                <input type='text' value='" . $member['char_id'] . "' style='width:70px;'>\n";
				$strHTML .= $strOffset . "              </td>\n";
				$strHTML .= $strOffset . "              <td>\n";
				$strHTML .= $strOffset . "                <input type='text' value='" . $member['recruiter_id'] . "' style='width:70px;'>\n";
				$strHTML .= $strOffset . "              </td>\n";
				$strHTML .= $strOffset . "              <td>\n";
				$strHTML .= $strOffset . "                <input type='text' value='" . $member['guild_status'] . "' style='width:55px;'>\n";
				$strHTML .= $strOffset . "              </td>\n";
				$strHTML .= $strOffset . "              <td>\n";
				$strHTML .= $strOffset . "                <input type='text' value='" . $member['points'] . "' style='width:40px;'>\n";
				$strHTML .= $strOffset . "              </td>\n";
				$strHTML .= $strOffset . "              <td>\n";
				$strHTML .= $strOffset . "                <input type='text' value='" . $member['rank_id'] . "' style='width:25px;'>\n";
				$strHTML .= $strOffset . "              </td>\n";
				$strHTML .= $strOffset . "              <td>\n";
				$strHTML .= $strOffset . "                <input type='text' value='" . $member['member_flags'] . "' style='width:35px;'>\n";
				$strHTML .= $strOffset . "              </td>\n";
				$strHTML .= $strOffset . "              <td>\n";
				$strHTML .= $strOffset . "                <input type='text' value='" . $member['join_date'] . "' style='width:85px;'>\n";
				$strHTML .= $strOffset . "              </td>\n";
				$strHTML .= $strOffset . "              <td>\n";
				$strHTML .= $strOffset . "                <input type='text' value='" . $member['note'] . "'>\n";
				$strHTML .= $strOffset . "              </td>\n";
				$strHTML .= $strOffset . "              <td>\n";
				$strHTML .= $strOffset . "                <input type='text' value='" . $member['officer_note'] . "'>\n";
				$strHTML .= $strOffset . "              </td>\n";
				//$strHTML .= $strOffset . "              <td>\n";
				//$strHTML .= $strOffset . "                <input type='text' value='" . $member['recruiting_message'] . "'>\n";
				//$strHTML .= $strOffset . "              </td>\n";
				$strHTML .= $strOffset . "              <td>\n";
				$strHTML .= $strOffset . "                <input type='text' value='binary data'>\n";
				$strHTML .= $strOffset . "              </td>\n";
				$strHTML .= $strOffset . "              <td>\n";
				$strHTML .= $strOffset . "                <input type='submit' name='cmd' value='Update'>\n";
				$strHTML .= $strOffset . "                <input type='submit' name='cmd' value='Delete'>\n";
				$strHTML .= $strOffset . "              </td>\n";
				$strHTML .= $strOffset . "            </tr>\n";
			}
			$strHTML .= $strOffset . "          </table>\n";
			$strHTML .= $strOffset . "        </fieldset>\n";
			break;
		case "guild_points":
			$strHTML .= $strOffset . "        <fieldset>\n";
			$strHTML .= $strOffset . "                  <legend>Points List</legend>\n";
			$strHTML .= $strOffset . "                  <table class='ContrastTable'>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>ID</th>\n";
			$strHTML .= $strOffset . "                      <th>Guild ID</th>\n";
			$strHTML .= $strOffset . "                      <th>Char ID</th>\n";
			$strHTML .= $strOffset . "                      <th>Date</th>\n";
			$strHTML .= $strOffset . "                      <th>Modified By</th>\n";
			$strHTML .= $strOffset . "                      <th>Comments</th>\n";
			$strHTML .= $strOffset . "                      <th>Points</th>\n";
			$strHTML .= $strOffset . "                      <th></th>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <td>\n";
			$strHTML .= $strOffset . "                        <input type='text' style='width:40px;'>\n";
			$strHTML .= $strOffset . "                      </td>\n";
			$strHTML .= $strOffset . "                      <td>\n";
			$strHTML .= $strOffset . "                        <input type='text' style='width:70px;'>\n";
			$strHTML .= $strOffset . "                      </td>\n";
			$strHTML .= $strOffset . "                      <td>\n";
			$strHTML .= $strOffset . "                        <input type='text' style='width:120px;'>\n";
			$strHTML .= $strOffset . "                      </td>\n";
			$strHTML .= $strOffset . "                      <td>\n";
			$strHTML .= $strOffset . "                        <input type='text' value='" . time() . "'style='width:85px;'>\n";
			$strHTML .= $strOffset . "                      </td>\n";
			$strHTML .= $strOffset . "                      <td>\n";
			$strHTML .= $strOffset . "                        <input type='text' style='width:70px;'>\n";
			$strHTML .= $strOffset . "                      </td>\n";
			$strHTML .= $strOffset . "                      <td>\n";
			$strHTML .= $strOffset . "                        <input type='text' style='width:300px;'>\n";
			$strHTML .= $strOffset . "                      </td>\n";
			$strHTML .= $strOffset . "                      <td>\n";
			$strHTML .= $strOffset . "                        <input type='text' style='width:40px;'>\n";
			$strHTML .= $strOffset . "                      </td>\n";
			$strHTML .= $strOffset . "                      <td>\n";
			$strHTML .= $strOffset . "                        <input type='submit' name='cmd' value='Insert'>\n";
			$strHTML .= $strOffset . "                      </td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                  </table>\n";
			$strHTML .= $strOffset . "        </fieldset>\n";
			break;
		case "guild_ranks":
			$strHTML .= $strOffset . "          <table>\n";
			$strHTML .= $strOffset . "            <tr>\n";
			$strHTML .= $strOffset . "              <td valign='top'>\n";
			$strHTML .= $strOffset . "                <fieldset>\n";
			$strHTML .= $strOffset . "                  <legend>Ranks</legend>\n";
			$strHTML .= $strOffset . "                  <table class='ContrastTable'>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th colspan='3'>Title</th>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <td>Icon</td>\n";
			$strHTML .= $strOffset . "                      <td>Name</td>\n";
			$strHTML .= $strOffset . "                      <td>Num</td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <td><img src='../images/guild_guildleader.png'></td>\n";
			$strHTML .= $strOffset . "                      <td>Guild Leader</td>\n";
			$strHTML .= $strOffset . "                      <td>17</td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <td><img src='../images/guild_officer.png'></td>\n";
			$strHTML .= $strOffset . "                      <td>Officer</td>\n";
			$strHTML .= $strOffset . "                      <td>2</td>\n";$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <td><img src='../images/guild_officeralt.png'></td>\n";
			$strHTML .= $strOffset . "                      <td>Officer Alt</td>\n";
			$strHTML .= $strOffset . "                      <td>3</td>\n";$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <td><img src='../images/guild_seniormember.png'></td>\n";
			$strHTML .= $strOffset . "                      <td>Senior Member</td>\n";
			$strHTML .= $strOffset . "                      <td>4</td>\n";$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <td><img src='../images/guild_member.png'></td>\n";
			$strHTML .= $strOffset . "                      <td>Member</td>\n";
			$strHTML .= $strOffset . "                      <td>9</td>\n";$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <td><img src='../images/guild_recruit.png'></td>\n";
			$strHTML .= $strOffset . "                      <td>Recruit</td>\n";
			$strHTML .= $strOffset . "                      <td>0</td>\n";$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <td><img src='../images/guild_newrecruit.png'></td>\n";
			$strHTML .= $strOffset . "                      <td>New Recruit</td>\n";
			$strHTML .= $strOffset . "                      <td>0</td>\n";$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <td><img src='../images/guild_penaltybox.png'></td>\n";
			$strHTML .= $strOffset . "                      <td>Penalty Box</td>\n";
			$strHTML .= $strOffset . "                      <td>1</td>\n";$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                  </table>\n";
			$strHTML .= $strOffset . "                </fieldset>\n";
			$strHTML .= $strOffset . "              </td>\n";
			$strHTML .= $strOffset . "              <td valign='top'>\n";
			$strHTML .= $strOffset . "                <fieldset>\n";
			$strHTML .= $strOffset . "                  <legend>Permissions</legend>\n";
			$strHTML .= $strOffset . "                  <table class='ContrastTable'>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th></th>\n";
			$strHTML .= $strOffset . "                      <td><img src='../images/guild_guildleader.png'></td>\n";
			$strHTML .= $strOffset . "                      <td><img src='../images/guild_officer.png'></td>\n";
			$strHTML .= $strOffset . "                      <td><img src='../images/guild_officeralt.png'></td>\n";
			$strHTML .= $strOffset . "                      <td><img src='../images/guild_seniormember.png'></td>\n";
			$strHTML .= $strOffset . "                      <td><img src='../images/guild_member.png'></td>\n";
			$strHTML .= $strOffset . "                      <td><img src='../images/guild_recruit.png'></td>\n";
			$strHTML .= $strOffset . "                      <td><img src='../images/guild_newrecruit.png'></td>\n";
			$strHTML .= $strOffset . "                      <td><img src='../images/guild_penaltybox.png'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Assign Guild Member Points</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Change Guild Heraldry</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Change Guild MOTD</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Change Permissions</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Change Rank Names</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Demote Guild Member</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Display Guild Heraldry</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Display Guild Name</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Edit Guild Event Filters</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Edit Guild Events</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Edit Guild Recruiting Settings</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Edit Officer Notes</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Edit Personal Notes</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Edit Personal Notes For Others</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Guild Bank 1: Deposit</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Guild Bank 1: See Contents</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Guild Bank 1: Withdraw</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Guild Bank 2: Deposit</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Guild Bank 2: See Contents</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Guild Bank 2: Withdraw</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Guild Bank 3: Deposit</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Guild Bank 3: See Contents</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Guild Bank 3: Withdraw</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Guild Bank 4: Deposit</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Guild Bank 4: See Contents</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Guild Bank 4: Withdraw</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Guild Bank: Set Withdrawal Limits</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Guild Hall Access: Friend</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Guild Hall Access: Trustee</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Guild Hall Access: Visitor</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Hide or Show Guild Achievements in Census</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Invite To Guild</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Make Others Guild Recruiters</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Manage Calendar Events</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Promote Guild Members</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Purchase Status Items</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Receive Guild Member Points</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Remove Guild Member</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>See All Recruiting Messages</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>See Guild Chat</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>See Officer Chat</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>See Officer Notes</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Send E-Mail to Guild</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Speak in Guild Chat</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <th>Speak In Officer Chat</th>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                      <td><input type='checkbox'></td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                    <tr>\n";
			$strHTML .= $strOffset . "                      <td colspan='9' align='center'>\n";
			$strHTML .= $strOffset . "                        <input type='submit' name='cmd' value='Update'>\n";
			$strHTML .= $strOffset . "                      </td>\n";
			$strHTML .= $strOffset . "                    </tr>\n";
			$strHTML .= $strOffset . "                  </table>\n";
			$strHTML .= $strOffset . "                </fieldset>\n";
			$strHTML .= $strOffset . "              </td>\n";
			$strHTML .= $strOffset . "            </tr>\n";
			break;
		case "guild_bank_settings":
			$strHTML .= $strOffset . "        <fieldset>\n";
			$strHTML .= $strOffset . "          <legend>Notice</legend>\n";
			$strHTML .= $strOffset . "          Not Currently Supported as part of EQ2Emu feature set\n";
			$strHTML .= $strOffset . "        </fieldset>\n";
			break;
		case "guild_recruiting":
			$strHTML .= $strOffset . "        <fieldset>\n";
			$strHTML .= $strOffset . "          <legend>Recruiting</legend>\n";
			$strHTML .= $strOffset . "          <table class='ContrastTable'>\n";
			$strHTML .= $strOffset . "            <tr>\n";
			$strHTML .= $strOffset . "              <th>Short Description</th>\n";
			$strHTML .= $strOffset . "              <td colspan='2'>\n";
			$strHTML .= $strOffset . "                <input type='text' value='" . $recruiting_data['short_desc'] . "' style='width:95%;'>\n";
			$strHTML .= $strOffset . "              </td>\n";
			$strHTML .= $strOffset . "              <td>\n";
			$strHTML .= $strOffset . "                <input type='submit' name='cmd' value='Update'>\n";
			$strHTML .= $strOffset . "              </td>\n";
			$strHTML .= $strOffset . "            </tr>\n";
			$strHTML .= $strOffset . "            <tr>\n";
			$strHTML .= $strOffset . "              <th>Full Description</th>\n";
			$strHTML .= $strOffset . "              <td colspan='2'>\n";
			$strHTML .= $strOffset . "                <textarea style='height:40px; width:95%'>" . $recruiting_data['full_desc'] . "</textarea>\n";
			$strHTML .= $strOffset . "              </td>\n";
			$strHTML .= $strOffset . "              <td></td>\n";
			$strHTML .= $strOffset . "            </tr>\n";
			$strHTML .= $strOffset . "            <tr>\n";
			$strHTML .= $strOffset . "              <th>Looking for</th>\n";
			$strHTML .= $strOffset . "              <td>\n";
			$strHTML .= $strOffset . "                <input type='checkbox'>Fighters |\n";
			$strHTML .= $strOffset . "                <input type='checkbox'>Priests |\n";
			$strHTML .= $strOffset . "                <input type='checkbox'>Scounts |\n";
			$strHTML .= $strOffset . "                <input type='checkbox'>Mages |\n";
			$strHTML .= $strOffset . "                <input type='checkbox'>Tradeskillers\n";
			$strHTML .= $strOffset . "              </td>\n";
			$strHTML .= $strOffset . "              <td>\n";
			$strHTML .= $strOffset . "                <input type='text' style='width:35px;'>\n";
			$strHTML .= $strOffset . "              </td>\n";
			$strHTML .= $strOffset . "              <th>\n";
			$strHTML .= $strOffset . "                Min Level\n";
			$strHTML .= $strOffset . "              </th>\n";
			$strHTML .= $strOffset . "            </tr>\n";
			$strHTML .= $strOffset . "            <tr>\n";
			$strHTML .= $strOffset . "              <th>Play Style</th>\n";
			$strHTML .= $strOffset . "              <td>\n";
			$strHTML .= $strOffset . "                <select style='width:80%;'>\n";
			$strHTML .= $strOffset . "                  <option>Casual</option>\n";
			$strHTML .= $strOffset . "                </select>\n";
			$strHTML .= $strOffset . "              </td>\n";
			$strHTML .= $strOffset . "              <td></td>\n";
			$strHTML .= $strOffset . "              <td></td>\n";
			$strHTML .= $strOffset . "            </tr>\n";
			$strHTML .= $strOffset . "            <tr>\n";
			$strHTML .= $strOffset . "              <th>Desc Tag1</th>\n";
			$strHTML .= $strOffset . "              <td>\n";
			$strHTML .= $strOffset . "                <select style='width:80%;'>\n";
			$strHTML .= $strOffset . "                  <option>We play at odd hours</option>\n";
			$strHTML .= $strOffset . "                </select>\n";
			$strHTML .= $strOffset . "              </td>\n";
			$strHTML .= $strOffset . "              <td></td>\n";
			$strHTML .= $strOffset . "              <td></td>\n";
			$strHTML .= $strOffset . "            </tr>\n";
			$strHTML .= $strOffset . "            <tr>\n";
			$strHTML .= $strOffset . "              <th>Desc Tag2</th>\n";
			$strHTML .= $strOffset . "              <td>\n";
			$strHTML .= $strOffset . "                <select style='width:80%;'>\n";
			$strHTML .= $strOffset . "                  <option>We enjoy doing quests</option>\n";
			$strHTML .= $strOffset . "                </select>\n";
			$strHTML .= $strOffset . "              </td>\n";
			$strHTML .= $strOffset . "              <td></td>\n";
			$strHTML .= $strOffset . "              <td></td>\n";
			$strHTML .= $strOffset . "            </tr>\n";
			$strHTML .= $strOffset . "            <tr>\n";
			$strHTML .= $strOffset . "              <th>Desc Tag3</th>\n";
			$strHTML .= $strOffset . "              <td>\n";
			$strHTML .= $strOffset . "                <select style='width:80%;'>\n";
			$strHTML .= $strOffset . "                  <option>We may use mature humor</option>\n";
			$strHTML .= $strOffset . "                </select>\n";
			$strHTML .= $strOffset . "              </td>\n";
			$strHTML .= $strOffset . "              <td></td>\n";
			$strHTML .= $strOffset . "              <td></td>\n";
			$strHTML .= $strOffset . "            </tr>\n";
			$strHTML .= $strOffset . "            <tr>\n";
			$strHTML .= $strOffset . "              <th>Desc Tag4</th>\n";
			$strHTML .= $strOffset . "              <td>\n";
			$strHTML .= $strOffset . "                <select style='width:80%;'>\n";
			$strHTML .= $strOffset . "                  <option>The inmates are funning the asylum</option>\n";
			$strHTML .= $strOffset . "                </select>\n";
			$strHTML .= $strOffset . "              </td>\n";
			$strHTML .= $strOffset . "              <td></td>\n";
			$strHTML .= $strOffset . "              <td></td>\n";
			$strHTML .= $strOffset . "            </tr>\n";
			$strHTML .= $strOffset . "          </table>\n";
			$strHTML .= $strOffset . "        </fieldset>\n";
			break;
		case "guild_achievements":
			$strHTML .= $strOffset . "        <fieldset>\n";
			$strHTML .= $strOffset . "          <legend>Notice</legend>\n";
			$strHTML .= $strOffset . "          !! The feature is currently under development !!<br>\n";
			$strHTML .= $strOffset . "          <a href='https://git.eq2emu.com/devn00b/EQ2EMu-Zeklabs-Editor/issues'>Progress can be tracked here</a>\n";
			$strHTML .= $strOffset . "        </fieldset>\n";
			break;
		default:
			$strHTML .= $strOffset . "        <fieldset>\n";
			$strHTML .= $strOffset . "          <legend>Guild Summary</legend>\n";
			$strHTML .= $strOffset . "          <table class='ContrastTable'>\n";
			$strHTML .= $strOffset . "            <tr>\n";
			$strHTML .= $strOffset . "              <th>ID</th>\n";
			$strHTML .= $strOffset . "              <th>Name</th>\n";
			$strHTML .= $strOffset . "              <th>MOTD</th>\n";
			$strHTML .= $strOffset . "              <th>Level</th>\n";
			$strHTML .= $strOffset . "              <th>XP</th>\n";
			$strHTML .= $strOffset . "              <th>XP Needed</th>\n";
			$strHTML .= $strOffset . "              <th>Formed On</th>\n";
			$strHTML .= $strOffset . "              <th></th>\n";
			$strHTML .= $strOffset . "            </tr>\n";
			$strHTML .= $strOffset . "            <form method='post' name='guilds|" . $guild_data['id'] . "'>\n";
			$strHTML .= $strOffset . "              <tr>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guilds|id' value='" . $guild_data['id'] . "' style='width:25px;' readonly>\n";
			$strHTML .= $strOffset . "                  <input type='hidden' name='orig_id' value='" . $guild_data['id'] . "'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guilds|name' value='" . $guild_data['name'] . "' style='width:200px;'>\n";
			$strHTML .= $strOffset . "                  <input type='hidden' name='orig_name' value='" . $guild_data['name'] . "'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guilds|motd' value='" . $guild_data['motd'] . "' style='width:250px;'>\n";
			$strHTML .= $strOffset . "                  <input type='hidden' name='orig_motd' value='" . $guild_data['motd'] . "'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guilds|level' value='" . $guild_data['level'] . "' style='width:30px;'>\n";
			$strHTML .= $strOffset . "                  <input type='hidden' name='orig_level' value='" . $guild_data['level'] . "'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guilds|xp' value='" . $guild_data['xp'] . "' style='width:40px;'>\n";
			$strHTML .= $strOffset . "                  <input type='hidden' name='orig_xp' value='" . $guild_data['xp'] . "'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guilds|xp_needed' value='" . $guild_data['xp_needed'] . "' style='width:70px;'>\n";
			$strHTML .= $strOffset . "                  <input type='hidden' name='orig_xp_needed' value='" . $guild_data['xp_needed'] . "'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='' value='" . $guild_data['date'] . "' style='width:70px;' readonly>\n";
			$strHTML .= $strOffset . "                  <input type='hidden' name='orig_formed_on' value='" . $guild_data['formed_on'] . "'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='hidden' name='table_name' value='guilds' />\n";
			$strHTML .= $strOffset . "                  <input type='hidden' name='idx_name' value='id' />\n";
			$strHTML .= $strOffset . "                  <input type='submit' name='cmd' value='Update'>\n";
			$strHTML .= $strOffset . "                  <input type='submit' name='cmd' value='Delete'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "              </tr>\n";
			$strHTML .= $strOffset . "            </form>\n";
			$strHTML .= $strOffset . "          </table>\n";
			$strHTML .= $strOffset . "        </fieldset>\n";
			//EVENTS SECTION
			$strHTML .= $strOffset . "        <fieldset>\n";
			$strHTML .= $strOffset . "          <legend>Guild Events</legend>\n";
			$strHTML .= $strOffset . "          <table class='ContrastTable'>\n";
			$strHTML .= $strOffset . "            <tr>\n";
			$strHTML .= $strOffset . "              <th>ID</th>\n";
			$strHTML .= $strOffset . "              <th>Guild ID</th>\n";
			$strHTML .= $strOffset . "              <th>Event ID</th>\n";
			$strHTML .= $strOffset . "              <th>Date</th>\n";
			$strHTML .= $strOffset . "              <th>Type</th>\n";
			$strHTML .= $strOffset . "              <th>Description</th>\n";
			$strHTML .= $strOffset . "              <th>Display</th>\n";
			$strHTML .= $strOffset . "              <th>Locked</th>\n";
			$strHTML .= $strOffset . "              <th>Archieved</th>\n";
			$strHTML .= $strOffset . "              <th></th>\n";
			$strHTML .= $strOffset . "            </tr>\n";
			$strHTML .= $strOffset . "            <form method='post' name='guild_events|new'>\n";
			$strHTML .= $strOffset . "              <tr>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  New\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guild_events|guild_id' value='" . $guild_data['id'] . "' style='width:30px;' readonly>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guild_events|event_id' value='" . (intval($event_max_data['max'])+1) . "' style='width:30px;' readonly>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guild_events|event_date' value='" . time() . "' style='width:80px;' readonly>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <select>\n";
			$strHTML .= $strOffset . "                    <option>SELECT</option>\n";
			foreach($event_type_data as $event_type)
			{
				$strHTML .= $strOffset . "                    <option value='" . $event_type['type_id'] . "'>" . $event_type['type_name'] . "</option>\n";
			}
			$strHTML .= $strOffset . "                  </select>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='text' name='guild_events|description' value='' style='width:325px;'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <select>\n";
			$strHTML .= $strOffset . "                    <option value='0'>No</option>\n";
			$strHTML .= $strOffset . "                    <option value='1' selected>Yes</option>\n";
			$strHTML .= $strOffset . "                  </select>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <select>\n";
			$strHTML .= $strOffset . "                    <option value='0'>No</option>\n";
			$strHTML .= $strOffset . "                    <option value='1'>Yes</option>\n";
			$strHTML .= $strOffset . "                  </select>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <select>\n";
			$strHTML .= $strOffset . "                    <option value='0'>No</option>\n";
			$strHTML .= $strOffset . "                    <option value='1'>Yes</option>\n";
			$strHTML .= $strOffset . "                  </select>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "                <td>\n";
			$strHTML .= $strOffset . "                  <input type='submit' name='cmd' value='Insert'>\n";
			$strHTML .= $strOffset . "                </td>\n";
			$strHTML .= $strOffset . "              </tr>\n";
			foreach($events_data as $event)
			{
				$strHTML .= $strOffset . "            <form method='post' name='events|" . $event['id'] . "'>\n";
				$strHTML .= $strOffset . "              <tr>\n";
				$strHTML .= $strOffset . "                <td>\n";
				$strHTML .= $strOffset . "                  <input type='text' name='guild_events|id' value='" . $event['id'] . "' style='width:40px;' readonly>\n";
				$strHTML .= $strOffset . "                  <input type='hidden' name='orig_id' value='" . $event['id'] . "'>\n";
				$strHTML .= $strOffset . "                </td>\n";
				$strHTML .= $strOffset . "                <td>\n";
				$strHTML .= $strOffset . "                  <input type='text' name='guild_events|guild_id' value='" . $event['guild_id'] . "' style='width:30px;' readonly>\n";
				$strHTML .= $strOffset . "                  <input type='hidden' name='orig_guild_id' value='" . $event['guild_id'] . "'>\n";
				$strHTML .= $strOffset . "                </td>\n";
				$strHTML .= $strOffset . "                <td>\n";
				$strHTML .= $strOffset . "                  <input type='text' name='guild_events|event_id' value='" . $event['event_id'] . "' style='width:30px;' readonly>\n";
				$strHTML .= $strOffset . "                  <input type='hidden' name='orig_event_id' value='" . $event['event_id'] . "'>\n";
				$strHTML .= $strOffset . "                </td>\n";
				$strHTML .= $strOffset . "                <td>\n";
				$strHTML .= $strOffset . "                  <input type='text' name='guild_events|event_date' value='" . $event['date'] . "' style='width:80px;' readonly>\n";
				$strHTML .= $strOffset . "                  <input type='hidden' name='orig_event_date' value='" . $event['event_date'] . "'>\n";
				$strHTML .= $strOffset . "                </td>\n";
				$strHTML .= $strOffset . "                <td>\n";
				$strHTML .= $strOffset . "                  <select>\n";
				$strHTML .= $strOffset . "                    <option>SELECT</option>\n";
				foreach($event_type_data as $event_type)
				{
					$isSelected = ($event_type['type_id'] == $event['event_type']?"selected":"");
					$strHTML .= $strOffset . "                    <option value='" . $event_type['type_id'] . "' " . $isSelected . ">" . $event_type['type_name'] . "</option>\n";
				}
				$strHTML .= $strOffset . "                  </select>\n";
				$strHTML .= $strOffset . "                </td>\n";
				$strHTML .= $strOffset . "                <td>\n";
				$strHTML .= $strOffset . "                  <input type='text' name='guild_events|description' value='" . $event['description'] . "' style='width:325px;'>\n";
				$strHTML .= $strOffset . "                  <input type='hidden' name='orig_description' value='" . $event['description'] . "'>\n";
				$strHTML .= $strOffset . "                </td>\n";
				$strHTML .= $strOffset . "                <td>\n";
				$strHTML .= $strOffset . "                  <select>\n";
				$strHTML .= $strOffset . "                    <option value='0'>No</option>\n";
				$strHTML .= $strOffset . "                    <option value='1' selected>Yes</option>\n";
				$strHTML .= $strOffset . "                  </select>\n";
				$strHTML .= $strOffset . "                </td>\n";
				$strHTML .= $strOffset . "                <td>\n";
				$strHTML .= $strOffset . "                  <select>\n";
				$strHTML .= $strOffset . "                    <option value='0'>No</option>\n";
				$strHTML .= $strOffset . "                    <option value='1'>Yes</option>\n";
				$strHTML .= $strOffset . "                  </select>\n";
				$strHTML .= $strOffset . "                </td>\n";
				$strHTML .= $strOffset . "                <td>\n";
				$strHTML .= $strOffset . "                  <select>\n";
				$strHTML .= $strOffset . "                    <option value='0'>No</option>\n";
				$strHTML .= $strOffset . "                    <option value='1'>Yes</option>\n";
				$strHTML .= $strOffset . "                  </select>\n";
				$strHTML .= $strOffset . "                </td>\n";
				$strHTML .= $strOffset . "                <td>\n";
				$strHTML .= $strOffset . "                  <input type='submit' name='cmd' value='Update'>\n";
				$strHTML .= $strOffset . "                  <input type='submit' name='cmd' value='Delete'>\n";
				$strHTML .= $strOffset . "                </td>\n";
				$strHTML .= $strOffset . "              </tr>\n";
			}
			$strHTML .= $strOffset . "            </table>\n";
			$strHTML .= $strOffset . "        </fieldset>\n";
			break;

	}
	$strHTML .= $strOffset . "      </fieldset>\n";
	$strHTML .= $strOffset . "    </td>\n";
	$strHTML .= $strOffset . "  </tr>\n";
	$strHTML .= $strOffset . "</table>\n";

}


print($strHTML);
include("footer.php");

?>